### PR TITLE
Websocket connection options

### PR DESCRIPTION
**Pull request by tomhouman**
- Forward WebSocket connection options to reconnect-ws when constructing KurentoClient instance.

### CODE REVIEW

**Comment by tgabi333** [comment]
This should solve https://github.com/Kurento/bugtracker/issues/67

**Comment by tomhouman** [comment]
Yes, this will solve bug #67. This enables full mutually authenticated TLS connections to KMS. You simply provide the proper socket options for your TLS configuration as you would with a standard socket. The reconnect library consumes the options and keeps the socket alive.

**Comment by tgabi333** [comment]
@tomhouman Could you please not merge master branch but rebase your commits onto master? Its could ease the pull request process.

**Comment by tomhouman** [comment]
@tgabi333 No problem, sorry I didn't notice the mess. Rebase is done.

**Comment by interfaith** [comment]
using "free" certs from startssl.com
all the demos give the same error with any kind of cert

janus did not have THIS bug.. but it does have android issues
every upgrade is a thrill

index.js:70 reconnect to server 22 10000 undefined
kurento-client.js:29012 WebSocket connection to 'wss://tra:8433/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
index.js:70 reconnect to server 23 10000 undefined
kurento-client.js:29012 WebSocket connection to 'wss://tra.com:8433/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
index.js:70 reconnect to server 24 10000 undefined
kurento-client.js:29012 WebSocket connection to 'wss://tra:8433/kurento' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by Nosere** [comment]
this issue is still not fixed

**Pull request merged**
