### PR TITLE
removed error-tojson dependency

### PR DESCRIPTION
**Pull request by marcosdourado**
## What is the new behavior provided by this change?

In 2016 a library was added to help stringify errors for better debugging[1].

However, when analyzing the kurento-client-js code, such a library is not used anywhere. Not only that, it alters the Error globally, causing conflicts with other libraries, making it impossible to be used together with kurento, as it happens for example with axios. The library was also abandoned and has not been updated for another four years [2].

As the library, besides being outdated, is not used and conflicts with other libraries, the suggestion is that it be removed.

This discussion started in the kurento group [3].

1. https://github.com/Kurento/kurento-client-js/commit/6dc7a8cd8cf88317775c3212b755d3772386f72b#diff-6d186b954a58d5bb740f73d84fe39073

2. https://github.com/AVVS/error-tojson

3. https://groups.google.com/g/kurento/c/p_N_ITKoRtI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / enhancement (non-breaking change which improves the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] My change requires a change to the documentation
- [ ] My change requires a change in other repository 

## Checklist

- [x] I have read the Contribution Guidelines 
- [x] I have added an explanation of what the changes do and why they should be included
- [x] I have written new tests for the changes, as applicable, and have successfully run them locally

### CODE REVIEW

**Comment by piranna** [comment]
> such a library is not used anywhere

That library adds a `toJson` method to `Error` objects, so although it doesn't export anything, it's being used in a transparent way for the developer just by `require()`ing it.


> The library was also abandoned and has not been updated for another four years

Not having updates in several years doesn't means it's abandoned if it just works. If you are so much concerned about that, just propose to replace it with https://www.npmjs.com/package/error-to-json, that has published 2.0.0 version just one week ago.

> such a library is not used anywhere

The library is being used each time an `Error` object is stringified. Instead of propose removing it, you should try to understand how it works first.

**Comment by j1elo** [comment]
I hadn't seen [error-tojson source code](https://github.com/AVVS/error-tojson/blob/master/index.js). @piranna is right, this is just adding a new `toJSON` method (note the full upper case) to the prototype of `Error`.

To provide more detailed context:

* Node uses exactly this name in its JSON stringifier code ([here](https://github.com/nodejs/node/blob/56967afdcab0b3c2dbcd120a0a761a041961754d/deps/v8/src/init/heap-symbols.h#L306), [here](https://github.com/nodejs/node/blob/56967afdcab0b3c2dbcd120a0a761a041961754d/deps/v8/src/json/json-stringifier.cc#L335)).
* I am not sure where exactly is this method triggered from kurento-client. The only point in code where I could find something is [here](https://github.com/Kurento/kurento-client-js/blob/f1dc6eed661f2ba6764fbda186ae343bb0417f55/lib/KurentoClient.js#L375), an `error.toString()`.

**Comment by marcosdourado** [comment]
@piranna 

In fact, I tried to understand how it works within the kurento client and found no mention or similar things, I even pointed this out in the kurento group.

Maybe error-to-json is a real alternative, looking at the code, it takes much more care than error-tojson, but I don't understand how this library works inside kurento so I don't know if it's a solution that won't cause problems.

Thank you :)

**Comment by j1elo** [comment]
Hey @marcosdourado,
I think https://github.com/AVVS/error-tojson is abandoned by its author, and anyways as you've mentioned this is a perfect case of absurdly small libraries that infects everything in the Node ecosystem. I propose that you copy this library locally as `kurento-client-js/lib/error-tojson.js`, which in its current state, it should work fine with the `writable: true`. If you open a PR with this I'll be glad to merge it.

**Comment by piranna** [comment]
> I propose that you copy this library locally as `kurento-client-js/lib/error-tojson.js`

I'm -1 for that, the correct thing would be to request the author to publish a new updated version, or fork it and publish it ourselves scoped, not to copy and embed the source code of a working standalone module inside the main one, that prevents reusability and helps nobody.

**Comment by j1elo** [comment]
In reality, I agree. In general terms, at least. But, in this specific case...

a) it's clear to me that the original author doesn't care any more about this lib. See for a proof what happened with AVVS/error-tojson#3, the PR is still today awaiting for a merge even though the requested changes were made. Also the fact that not even the latest changes, which were important, got ever released to NPM.

b) it's such a small piece of code that there is not much value in it. If I was writing the kurento-client-js code from scratch, I would probably just have written this code as a helper module, not even occurring to me the possibility of looking for a 3rd-party dependency.

c) I'm currently not willing to maintain (yet another) fork. It would get abandoned pretty much instantly. And that's fine, the community seems to have converged upon other libs, anyway.

d) Just doing the research and writing the messages in this thread has already consumed collectively for all of us something like 1000x the time it would save for anybody to have this in a well-updated and well-maintained library!

**Pull request closed without merging**
